-- hucolor.nvim · 插件高亮组
local hucolor = require("hucolor.colors")
local style = require("hucolor.style")

local M = {}

M.load = function()
	local plugins = {

		-- GitSigns / GitGutter
		GitSignsAdd = { fg = hucolor.green },
		GitSignsAddNr = { fg = hucolor.green },
		GitSignsAddLn = { fg = hucolor.green },
		GitSignsChange = { fg = hucolor.yellow },
		GitSignsChangeNr = { fg = hucolor.yellow },
		GitSignsChangeLn = { fg = hucolor.yellow },
		GitSignsDelete = { fg = hucolor.red },
		GitSignsDeleteNr = { fg = hucolor.red },
		GitSignsDeleteLn = { fg = hucolor.red },
		GitSignsCurrentLineBlame = { fg = hucolor.fg3, style = style.bold },
		GitGutterAdd = { fg = hucolor.green },
		GitGutterChange = { fg = hucolor.yellow },
		GitGutterDelete = { fg = hucolor.red },

		-- Telescope
		TelescopePromptBorder = { fg = hucolor.fg2 },
		TelescopeResultsBorder = { fg = hucolor.fg2 },
		TelescopePreviewBorder = { fg = hucolor.fg2 },
		TelescopeSelectionCaret = { fg = hucolor.orange },
		TelescopeSelection = { fg = hucolor.bg0, bg = hucolor.blue },
		TelescopeMatching = { link = "Search" },
		TelescopePromptPrefix = { fg = hucolor.orange },
		TelescopePromptTitle = { fg = hucolor.bg0, bg = hucolor.orange },
		TelescopeResultsTitle = { fg = hucolor.bg0, bg = hucolor.blue },
		TelescopePreviewTitle = { fg = hucolor.bg0, bg = hucolor.green },

		-- NvimTree
		NvimTreeRootFolder = { fg = hucolor.yellow },
		NvimTreeSymlink = { fg = hucolor.blue_bright },
		NvimTreeFolderName = { fg = hucolor.blue },
		NvimTreeFolderIcon = { fg = hucolor.blue },
		NvimTreeEmptyFolderName = { fg = hucolor.fg1 },
		NvimTreeOpenedFolderName = { fg = hucolor.blue_bright },
		NvimTreeExecFile = { fg = hucolor.fg1 },
		NvimTreeOpenedFile = { fg = hucolor.fg0 },
		NvimTreeSpecialFile = { fg = hucolor.blue, style = style.bold },
		NvimTreeImageFile = { fg = hucolor.fg1 },
		NvimTreeMarkdownFile = { fg = hucolor.fg1 },
		NvimTreeIndentMarker = { fg = hucolor.fg3 },
		NvimTreeGitDirty = { fg = hucolor.yellow },
		NvimTreeGitStaged = { fg = hucolor.yellow },
		NvimTreeGitMerge = { fg = hucolor.yellow },
		NvimTreeGitRenamed = { fg = hucolor.yellow },
		NvimTreeGitNew = { fg = hucolor.green },
		NvimTreeGitDeleted = { fg = hucolor.red },
		NvimTreeGitIgnored = { fg = hucolor.fg3 },

		-- WhichKey
		WhichKey = { fg = hucolor.orange, style = style.bold },
		WhichKeyGroup = { fg = hucolor.fg0 },
		WhichKeyDesc = { fg = hucolor.cyan, style = style.italic },
		WhichKeySeperator = { fg = hucolor.blue },
		WhichKeyFloating = { bg = hucolor.bg1 },
		WhichKeyFloat = { bg = hucolor.bg1 },
		WhichKeyValue = { fg = hucolor.green },

		-- nvim-cmp
		CmpItemAbbr = { fg = hucolor.fg1 },
		CmpItemAbbrMatch = { fg = hucolor.blue, style = style.bold },
		CmpItemAbbrMatchFuzzy = { fg = hucolor.blue, style = style.bold },
		CmpItemMenu = { fg = hucolor.fg3 },
		CmpItemKind = { fg = hucolor.purple },
		CmpItemKindClass = { fg = hucolor.blue },
		CmpItemKindColor = { fg = hucolor.purple },
		CmpItemKindConstant = { fg = hucolor.yellow },
		CmpItemKindConstructor = { fg = hucolor.blue },
		CmpItemKindEnum = { fg = hucolor.blue },
		CmpItemKindEnumMember = { fg = hucolor.blue_bright },
		CmpItemKindEvent = { fg = hucolor.blue },
		CmpItemKindField = { fg = hucolor.fg1 },
		CmpItemKindFile = { fg = hucolor.fg1 },
		CmpItemKindFolder = { fg = hucolor.blue },
		CmpItemKindFunction = { fg = hucolor.orange },
		CmpItemKindInterface = { fg = hucolor.blue },
		CmpItemKindKeyword = { fg = hucolor.blue },
		CmpItemKindMethod = { fg = hucolor.orange },
		CmpItemKindModule = { fg = hucolor.fg0 },
		CmpItemKindOperator = { fg = hucolor.blue },
		CmpItemKindProperty = { fg = hucolor.blue, style = style.italic },
		CmpItemKindReference = { fg = hucolor.purple },
		CmpItemKindSnippet = { fg = hucolor.cyan },
		CmpItemKindStruct = { fg = hucolor.blue },
		CmpItemKindText = { fg = hucolor.fg1 },
		CmpItemKindTypeParameter = { fg = hucolor.blue_bright },
		CmpItemKindUnit = { fg = hucolor.fg1 },
		CmpItemKindValue = { fg = hucolor.purple },
		CmpItemKindVariable = { fg = hucolor.fg1 },

		-- indent-blankline（新旧两代命名）
		IndentBlanklineChar = { fg = hucolor.bg3 },
		IndentBlanklineContextChar = { fg = hucolor.blue_bright },
		IblIndent = { fg = hucolor.bg3 },
		IblScope = { fg = hucolor.fg2 },

		-- nvim-notify
		NotifyDEBUGBorder = { fg = hucolor.fg3 },
		NotifyDEBUGIcon = { fg = hucolor.fg3 },
		NotifyDEBUGTitle = { fg = hucolor.fg3 },
		NotifyERRORBorder = { fg = hucolor.red },
		NotifyERRORIcon = { fg = hucolor.red },
		NotifyERRORTitle = { fg = hucolor.red },
		NotifyINFOBorder = { fg = hucolor.blue },
		NotifyINFOIcon = { fg = hucolor.blue },
		NotifyINFOTitle = { fg = hucolor.blue },
		NotifyTRACEBorder = { fg = hucolor.purple },
		NotifyTRACEIcon = { fg = hucolor.purple },
		NotifyTRACETitle = { fg = hucolor.purple },
		NotifyWARNBorder = { fg = hucolor.yellow },
		NotifyWARNIcon = { fg = hucolor.yellow },
		NotifyWARNTitle = { fg = hucolor.yellow },

		-- mini.nvim
		MiniCompletionActiveParameter = { style = "underline" },
		MiniCursorword = { bg = hucolor.bg3 },
		MiniCursorwordCurrent = { bg = hucolor.bg3 },
		MiniIndentscopeSymbol = { fg = hucolor.blue_bright },
		MiniIndentscopePrefix = { style = "nocombine" },
		MiniJump = { fg = hucolor.bg0, bg = hucolor.blue },
		MiniJump2dSpot = { fg = hucolor.orange, style = "bold,nocombine" },
		MiniStarterCurrent = { style = "nocombine" },
		MiniStarterFooter = { fg = hucolor.green, style = style.italic },
		MiniStarterHeader = { fg = hucolor.blue },
		MiniStarterInactive = { link = "Comment" },
		MiniStarterItem = { link = "Normal" },
		MiniStarterItemBullet = { fg = hucolor.fg1 },
		MiniStarterItemPrefix = { fg = hucolor.purple },
		MiniStarterSection = { fg = hucolor.fg1 },
		MiniStarterQuery = { fg = hucolor.blue_bright },
		MiniStatuslineDevinfo = { fg = hucolor.fg1, bg = hucolor.bg2 },
		MiniStatuslineFileinfo = { fg = hucolor.fg1, bg = hucolor.bg2 },
		MiniStatuslineFilename = { fg = hucolor.fg1, bg = hucolor.bg1 },
		MiniStatuslineInactive = { fg = hucolor.fg1, bg = hucolor.bg0, style = style.bold },
		MiniStatuslineModeCommand = { fg = hucolor.bg0, bg = hucolor.yellow, style = style.bold },
		MiniStatuslineModeInsert = { fg = hucolor.bg0, bg = hucolor.green, style = style.bold },
		MiniStatuslineModeNormal = { fg = hucolor.bg0, bg = hucolor.blue, style = style.bold },
		MiniStatuslineModeOther = { fg = hucolor.bg0, bg = hucolor.purple, style = style.bold },
		MiniStatuslineModeReplace = { fg = hucolor.bg0, bg = hucolor.red, style = style.bold },
		MiniStatuslineModeVisual = { fg = hucolor.bg0, bg = hucolor.orange, style = style.bold },
		MiniSurround = { link = "IncSearch" },
		MiniTablineCurrent = { bg = hucolor.bg1 },
		MiniTablineFill = { link = "TabLineFill" },
		MiniTablineHidden = { bg = hucolor.bg0, fg = hucolor.fg3 },
		MiniTablineModifiedCurrent = { bg = hucolor.bg1, fg = hucolor.yellow },
		MiniTablineModifiedHidden = { bg = hucolor.bg0, fg = hucolor.yellow },
		MiniTablineModifiedVisible = { bg = hucolor.bg2, fg = hucolor.yellow },
		MiniTablineTabpagesection = { fg = hucolor.blue, bg = hucolor.fg0, style = style.reverse_bold },
		MiniTablineVisible = { bg = hucolor.bg2 },
		MiniTestEmphasis = { style = style.bold },
		MiniTestFail = { fg = hucolor.red, style = style.bold },
		MiniTestPass = { fg = hucolor.green, style = style.bold },
		MiniTrailspace = { bg = hucolor.red },

		-- headlines.nvim（bg 为 bg0 与标题色的 10:1 混色，随新 bg0 重算）
		Headline1 = { fg = hucolor.orange, bg = "#362f2d", style = style.bold },
		Headline2 = { fg = hucolor.yellow, bg = "#352f2a", style = style.bold },
		Headline3 = { fg = hucolor.green, bg = "#27322e", style = style.bold },
		Headline4 = { fg = hucolor.blue, bg = "#2f2f3c", style = style.bold },
		Headline5 = { fg = hucolor.purple, bg = "#322d3a", style = style.bold },
		Headline6 = { fg = hucolor.blue_bright, bg = "#33333c", style = style.bold },
		Quote = { fg = hucolor.fg2 },
		CodeBlock = { bg = hucolor.bg1 },
		Dash = { fg = hucolor.blue, style = style.bold },

		-- illuminate
		illuminatedWord = { bg = hucolor.bg3 },
		illuminatedCurWord = { bg = hucolor.bg3 },
		IlluminatedWordText = { bg = hucolor.bg3 },
		IlluminatedWordRead = { bg = hucolor.bg3 },
		IlluminatedWordWrite = { bg = hucolor.bg3 },

		-- leap.nvim
		LeapMatch = { style = "underline,nocombine", fg = hucolor.yellow },
		LeapLabelPrimary = { style = "nocombine", fg = hucolor.bg0, bg = hucolor.yellow },
		LeapLabelSecondary = { style = "nocombine", fg = hucolor.bg0, bg = hucolor.purple },

		-- hop.nvim
		HopNextKey = { fg = hucolor.orange, style = style.bold },
		HopNextKey1 = { fg = hucolor.cyan, style = style.bold },
		HopNextKey2 = { fg = hucolor.fg1 },
		HopUnmatched = { fg = hucolor.fg3 },

		-- flash.nvim
		FlashLabel = { fg = hucolor.bg0, bg = hucolor.yellow },
		FlashMatch = { fg = hucolor.yellow, style = "underline,nocombine" },
		FlashCursor = { fg = hucolor.bg0, bg = hucolor.orange },
		FlashBackdrop = { fg = hucolor.fg3 },

		-- vim-sneak
		Sneak = { fg = hucolor.bg0, bg = hucolor.blue },
		SneakScope = { bg = hucolor.bg1 },

		-- rainbow-delimiters.nvim
		RainbowDelimiterRed = { fg = hucolor.red },
		RainbowDelimiterYellow = { fg = hucolor.yellow },
		RainbowDelimiterBlue = { fg = hucolor.blue },
		RainbowDelimiterOrange = { fg = hucolor.orange },
		RainbowDelimiterGreen = { fg = hucolor.green },
		RainbowDelimiterCyan = { fg = hucolor.cyan },
		RainbowDelimiterViolet = { fg = hucolor.purple },

		-- nvim-ts-rainbow
		rainbowcol1 = { fg = hucolor.purple },
		rainbowcol2 = { fg = hucolor.yellow },
		rainbowcol3 = { fg = hucolor.red },
		rainbowcol4 = { fg = hucolor.cyan },
		rainbowcol5 = { fg = hucolor.green },
		rainbowcol6 = { fg = hucolor.blue_bright },
		rainbowcol7 = { fg = hucolor.orange },

		-- aerial.nvim
		AerialLine = { bg = hucolor.bg2 },
		AerialLineNC = { bg = hucolor.bg2 },
		AerialArrayIcon = { fg = hucolor.yellow },
		AerialBooleanIcon = { fg = hucolor.blue_bright, style = style.bold },
		AerialClassIcon = { fg = hucolor.blue },
		AerialConstantIcon = { fg = hucolor.yellow },
		AerialConstructorIcon = { fg = hucolor.blue },
		AerialEnumIcon = { fg = hucolor.blue },
		AerialEnumMemberIcon = { fg = hucolor.blue_bright },
		AerialEventIcon = { fg = hucolor.blue },
		AerialFieldIcon = { fg = hucolor.fg1 },
		AerialFileIcon = { fg = hucolor.green },
		AerialFunctionIcon = { fg = hucolor.orange },
		AerialInterfaceIcon = { fg = hucolor.blue },
		AerialKeyIcon = { fg = hucolor.blue },
		AerialMethodIcon = { fg = hucolor.orange },
		AerialModuleIcon = { fg = hucolor.fg0 },
		AerialNamespaceIcon = { fg = hucolor.fg0 },
		AerialNullIcon = { fg = hucolor.blue },
		AerialNumberIcon = { fg = hucolor.purple },
		AerialObjectIcon = { fg = hucolor.blue },
		AerialOperatorIcon = { fg = hucolor.blue },
		AerialPackageIcon = { fg = hucolor.fg0 },
		AerialPropertyIcon = { fg = hucolor.blue, style = style.italic },
		AerialStringIcon = { fg = hucolor.green },
		AerialStructIcon = { fg = hucolor.blue },
		AerialTypeParameterIcon = { fg = hucolor.blue_bright },
		AerialVariableIcon = { fg = hucolor.fg1, style = style.bold },
		AerialArray = { fg = hucolor.yellow },
		AerialBoolean = { fg = hucolor.blue_bright, style = style.bold },
		AerialClass = { fg = hucolor.blue },
		AerialConstant = { fg = hucolor.yellow },
		AerialConstructor = { fg = hucolor.blue },
		AerialEnum = { fg = hucolor.blue },
		AerialEnumMember = { fg = hucolor.blue_bright },
		AerialEvent = { fg = hucolor.blue },
		AerialField = { fg = hucolor.fg1 },
		AerialFile = { fg = hucolor.green },
		AerialFunction = { fg = hucolor.orange },
		AerialInterface = { fg = hucolor.blue },
		AerialKey = { fg = hucolor.blue },
		AerialMethod = { fg = hucolor.orange },
		AerialModule = { fg = hucolor.fg0 },
		AerialNamespace = { fg = hucolor.fg0 },
		AerialNull = { fg = hucolor.blue },
		AerialNumber = { fg = hucolor.purple },
		AerialObject = { fg = hucolor.blue },
		AerialOperator = { fg = hucolor.blue },
		AerialPackage = { fg = hucolor.fg0 },
		AerialProperty = { fg = hucolor.blue, style = style.italic },
		AerialString = { fg = hucolor.green },
		AerialStruct = { fg = hucolor.blue },
		AerialTypeParameter = { fg = hucolor.blue_bright },
		AerialVariable = { fg = hucolor.fg1, style = style.bold },

		-- nvim-navic
		NavicIconsArray = { fg = hucolor.yellow },
		NavicIconsBoolean = { fg = hucolor.blue_bright, style = style.bold },
		NavicIconsClass = { fg = hucolor.blue },
		NavicIconsConstant = { fg = hucolor.yellow },
		NavicIconsConstructor = { fg = hucolor.blue },
		NavicIconsEnum = { fg = hucolor.blue },
		NavicIconsEnumMember = { fg = hucolor.blue_bright },
		NavicIconsEvent = { fg = hucolor.blue },
		NavicIconsField = { fg = hucolor.fg1 },
		NavicIconsFile = { fg = hucolor.green },
		NavicIconsFunction = { fg = hucolor.orange },
		NavicIconsInterface = { fg = hucolor.blue },
		NavicIconsKey = { fg = hucolor.blue },
		NavicIconsMethod = { fg = hucolor.orange },
		NavicIconsModule = { fg = hucolor.fg0 },
		NavicIconsNamespace = { fg = hucolor.fg0 },
		NavicIconsNull = { fg = hucolor.blue },
		NavicIconsNumber = { fg = hucolor.purple },
		NavicIconsObject = { fg = hucolor.blue },
		NavicIconsOperator = { fg = hucolor.blue },
		NavicIconsPackage = { fg = hucolor.fg0 },
		NavicIconsProperty = { fg = hucolor.blue, style = style.italic },
		NavicIconsString = { fg = hucolor.green },
		NavicIconsStruct = { fg = hucolor.blue },
		NavicIconsTypeParameter = { fg = hucolor.blue_bright },
		NavicIconsVariable = { fg = hucolor.fg1, style = style.bold },
		NavicText = { fg = hucolor.fg1 },
		NavicSeparator = { fg = hucolor.fg2 },

		-- nvim-dap
		DapBreakpoint = { fg = hucolor.green },
		DapStopped = { fg = hucolor.yellow },
		DapUIVariable = { fg = hucolor.fg1 },
		DapUIScope = { fg = hucolor.orange },
		DapUIType = { fg = hucolor.blue },
		DapUIValue = { fg = hucolor.fg1 },
		DapUIModifiedValue = { fg = hucolor.orange },
		DapUIDecoration = { fg = hucolor.orange },
		DapUIThread = { fg = hucolor.blue },
		DapUIStoppedThread = { fg = hucolor.blue_bright },
		DapUIFrameName = { fg = hucolor.fg1 },
		DapUISource = { fg = hucolor.blue },
		DapUILineNumber = { fg = hucolor.orange },
		DapUIFloatBorder = { fg = hucolor.orange },
		DapUIWatchesEmpty = { fg = hucolor.red },
		DapUIWatchesValue = { fg = hucolor.orange },
		DapUIWatchesError = { fg = hucolor.red },
		DapUIBreakpointsPath = { fg = hucolor.orange },
		DapUIBreakpointsInfo = { fg = hucolor.orange },
		DapUIBreakpointsCurrentLine = { fg = hucolor.orange },
		DapUIBreakpointsLine = { fg = hucolor.orange },

		-- Neogit
		NeogitBranch = { fg = hucolor.blue },
		NeogitRemote = { fg = hucolor.cyan },
		NeogitHunkHeader = { fg = hucolor.cyan },
		NeogitHunkHeaderHighlight = { fg = hucolor.cyan, bg = hucolor.bg1 },
		NeogitDiffContextHighlight = { bg = hucolor.bg1 },
		NeogitDiffDeleteHighlight = { fg = hucolor.red, style = "reverse" },
		NeogitDiffAddHighlight = { fg = hucolor.green, style = "reverse" },

		-- lsp-trouble
		LspTroubleText = { fg = hucolor.fg1 },
		LspTroubleCount = { fg = hucolor.bg0, bg = hucolor.blue },
		LspTroubleNormal = { fg = hucolor.fg1, bg = hucolor.sidebar },

		-- noice.nvim
		NoiceCmdlinePopup = { bg = hucolor.bg1 },
		NoiceCmdlinePopupBorder = { fg = hucolor.blue },
		NoiceCmdlineIcon = { fg = hucolor.orange },
		NoiceFormatProgressDone = { fg = hucolor.green },
		NoiceFormatProgressTodo = { fg = hucolor.fg3 },
		NoicePopupmenu = { bg = hucolor.bg1 },
		NoicePopupmenuBorder = { fg = hucolor.fg2 },

		-- treesitter-context
		TreesitterContext = { bg = hucolor.bg1 },
		TreesitterContextLineNumber = { fg = hucolor.fg3 },

		-- copilot
		CopilotLabel = { fg = hucolor.fg2, bg = hucolor.none },

		-- 自定义状态栏组（供 lualine/staline 等引用）
		StatusLineDull = { fg = hucolor.fg3, bg = hucolor.bg1 },
		StatusLineAccent = { fg = hucolor.bg0, bg = hucolor.orange },
	}

	-- 侧栏背景选项
	if vim.g.hucolor_disable_background then
		plugins.NvimTreeNormal = { fg = hucolor.fg1, bg = hucolor.none }
	elseif vim.g.hucolor_enable_sidebar_background then
		plugins.NvimTreeNormal = { fg = hucolor.fg1, bg = hucolor.sidebar }
	else
		plugins.NvimTreeNormal = { fg = hucolor.fg1, bg = hucolor.none }
	end

	return plugins
end

return M
