-- hucolor.nvim · TreeSitter 高亮组（旧 TS* 名 + 现代 @capture 名）
local hucolor = require("hucolor.colors")
local style = require("hucolor.style")

local M = {}

M.load = function()
	local treesitter = {
		TSAnnotation = { fg = hucolor.purple }, -- For C++/Dart attributes, annotations
		TSAttribute = { fg = hucolor.purple },
		TSBoolean = { fg = hucolor.blue_bright, style = style.bold },
		TSCharacter = { fg = hucolor.green, style = style.italic },
		TSComment = { fg = hucolor.fg2, style = style.italic },
		TSConditional = { fg = hucolor.blue, style = style.italic },
		TSConstBuiltin = { fg = hucolor.blue_bright, style = style.bold },
		TSConstMacro = { fg = hucolor.blue_bright, style = style.bold },
		TSConstant = { fg = hucolor.fg0 },
		TSConstructor = { fg = hucolor.blue },
		TSEmphasis = { fg = hucolor.blue, style = style.italic },
		TSError = { fg = hucolor.red },
		TSException = { fg = hucolor.yellow },
		TSField = { fg = hucolor.fg1, style = style.italic },
		TSFloat = { fg = hucolor.purple },
		TSFuncBuiltin = { fg = hucolor.rose, style = style.italic },
		TSFuncMacro = { fg = hucolor.rose, style = style.italic },
		TSFunction = { fg = hucolor.rose, style = style.italic },
		TSInclude = { fg = hucolor.blue },
		TSKeyword = { fg = hucolor.blue, style = style.italic },
		TSKeywordFunction = { fg = hucolor.blue, style = style.italic },
		TSKeywordOperator = { fg = hucolor.blue, style = style.italic },
		TSKeywordReturn = { fg = hucolor.blue, style = style.italic },
		TSLabel = { fg = hucolor.yellow },
		TSLiteral = { fg = hucolor.fg1 },
		TSMethod = { fg = hucolor.rose, style = style.italic },
		TSNamespace = { fg = hucolor.fg0, style = style.italic },
		TSNumber = { fg = hucolor.purple },
		TSOperator = { fg = hucolor.blue },
		TSParameter = { fg = hucolor.fg1, style = style.italic },
		TSParameterReference = { fg = hucolor.fg1, style = style.italic },
		TSProperty = { fg = hucolor.blue, style = style.italic },
		TSPunctBracket = { fg = hucolor.fg2 },
		TSPunctDelimiter = { fg = hucolor.fg2 },
		TSPunctSpecial = { fg = hucolor.fg2 },
		TSRepeat = { fg = hucolor.blue, style = style.italic },
		TSString = { fg = hucolor.green, style = style.italic },
		TSStringEscape = { fg = hucolor.yellow, style = style.italic },
		TSStringRegex = { fg = hucolor.cyan, style = style.italic },
		TSSymbol = { fg = hucolor.purple },
		TSTag = { fg = hucolor.blue },
		TSTagDelimiter = { fg = hucolor.fg2 },
		TSText = { fg = hucolor.fg1 },
		TSTextReference = { fg = hucolor.purple, style = style.bold },
		TSTitle = { fg = hucolor.rose, bg = hucolor.none, style = style.bold },
		TSType = { fg = hucolor.blue },
		TSTypeBuiltin = { fg = hucolor.blue },
		TSUnderline = { fg = hucolor.fg1, style = "underline" },
		TSURI = { fg = hucolor.green, style = "underline" },
		TSVariable = { fg = hucolor.fg1 },
		TSVariableBuiltin = { fg = hucolor.fg0, style = style.bold },
	}

	local captures = {
		["@annotation"] = { fg = hucolor.purple },
		["@attribute"] = { fg = hucolor.purple },
		["@boolean"] = { fg = hucolor.blue_bright, style = style.bold },
		["@character"] = { fg = hucolor.green, style = style.italic },
		["@character.special"] = { fg = hucolor.yellow, style = style.italic },
		["@comment"] = { fg = hucolor.fg2, style = style.italic },
		["@conditional"] = { fg = hucolor.blue, style = style.italic },
		["@constant"] = { fg = hucolor.fg0 },
		["@constant.builtin"] = { fg = hucolor.blue_bright, style = style.bold },
		["@constant.macro"] = { fg = hucolor.blue_bright, style = style.bold },
		["@constructor"] = { fg = hucolor.blue },
		["@debug"] = { fg = hucolor.red },
		["@define"] = { fg = hucolor.yellow },
		["@error"] = { fg = hucolor.red },
		["@exception"] = { fg = hucolor.yellow },
		["@field"] = { fg = hucolor.fg1, style = style.italic },
		["@float"] = { fg = hucolor.purple },
		["@function"] = { fg = hucolor.rose, style = style.italic },
		["@function.builtin"] = { fg = hucolor.rose, style = style.italic },
		["@function.call"] = { fg = hucolor.rose, style = style.italic },
		["@function.macro"] = { fg = hucolor.rose, style = style.italic },
		["@function.method"] = { fg = hucolor.rose, style = style.italic },
		["@function.method.call"] = { fg = hucolor.rose, style = style.italic },
		["@include"] = { fg = hucolor.blue },
		["@keyword"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.conditional"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.coroutine"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.debug"] = { fg = hucolor.red },
		["@keyword.exception"] = { fg = hucolor.yellow },
		["@keyword.function"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.import"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.operator"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.repeat"] = { fg = hucolor.blue, style = style.italic },
		["@keyword.return"] = { fg = hucolor.blue, style = style.italic },
		["@label"] = { fg = hucolor.yellow },
		["@method"] = { fg = hucolor.rose, style = style.italic },
		["@method.call"] = { fg = hucolor.rose, style = style.italic },
		["@namespace"] = { fg = hucolor.fg0, style = style.italic },
		["@none"] = { fg = hucolor.fg1 },
		["@number"] = { fg = hucolor.purple },
		["@number.float"] = { fg = hucolor.purple },
		["@operator"] = { fg = hucolor.blue },
		["@parameter"] = { fg = hucolor.fg1, style = style.italic },
		["@parameter.reference"] = { fg = hucolor.fg1, style = style.italic },
		["@preproc"] = { fg = hucolor.yellow },
		["@property"] = { fg = hucolor.blue, style = style.italic },
		["@punctuation.bracket"] = { fg = hucolor.fg2 },
		["@punctuation.delimiter"] = { fg = hucolor.fg2 },
		["@punctuation.special"] = { fg = hucolor.fg2 },
		["@repeat"] = { fg = hucolor.blue, style = style.italic },
		["@storageclass"] = { fg = hucolor.blue },
		["@string"] = { fg = hucolor.green, style = style.italic },
		["@string.documentation"] = { fg = hucolor.green, style = style.italic },
		["@string.escape"] = { fg = hucolor.yellow, style = style.italic },
		["@string.regex"] = { fg = hucolor.cyan, style = style.italic },
		["@string.special"] = { fg = hucolor.yellow, style = style.italic },
		["@string.symbol"] = { fg = hucolor.purple },
		["@symbol"] = { fg = hucolor.purple },
		["@tag"] = { fg = hucolor.blue },
		["@tag.attribute"] = { fg = hucolor.yellow },
		["@tag.delimiter"] = { fg = hucolor.fg2 },
		["@text"] = { fg = hucolor.fg1 },
		["@text.danger"] = { fg = hucolor.red },
		["@text.diff.add"] = { fg = hucolor.green },
		["@text.diff.delete"] = { fg = hucolor.red },
		["@text.emphasis"] = { fg = hucolor.blue, style = style.italic },
		["@text.environment"] = { fg = hucolor.blue },
		["@text.environment.name"] = { fg = hucolor.orange, style = style.bold },
		["@text.literal"] = { fg = hucolor.fg1 },
		["@text.math"] = { fg = hucolor.cyan },
		["@text.note"] = { fg = hucolor.blue },
		["@text.reference"] = { fg = hucolor.purple, style = style.bold },
		["@text.strike"] = { fg = hucolor.fg1, style = "strikethrough" },
		["@text.strong"] = { fg = hucolor.orange, style = style.bold },
		["@text.title"] = { fg = hucolor.rose, style = style.bold },
		["@text.underline"] = { fg = hucolor.fg1, style = "underline" },
		["@text.uri"] = { fg = hucolor.green, style = "underline" },
		["@text.warning"] = { fg = hucolor.yellow },
		["@type"] = { fg = hucolor.blue },
		["@type.builtin"] = { fg = hucolor.blue },
		["@type.definition"] = { fg = hucolor.blue },
		["@type.qualifier"] = { fg = hucolor.blue, style = style.italic },
		["@variable"] = { fg = hucolor.fg1 },
		["@variable.builtin"] = { fg = hucolor.fg0, style = style.bold },
		["@variable.global"] = { fg = hucolor.fg1 },
		["@variable.member"] = { fg = hucolor.fg1, style = style.italic },
		["@variable.parameter"] = { fg = hucolor.fg1, style = style.italic },
	}

	return vim.tbl_extend("force", treesitter, captures)
end

return M
